env:
    global:
        - PATH=$HOME/.local/bin:$PATH

services:
    - docker

before_install:
    - pip install --user awscli

install:
    - docker run -v $(pwd):/app -w /app node:8 npm install

script:
    - docker run -v $(pwd):/app -w /app node:8 ./node_modules/.bin/ng build --prod --aot

deploy:
    provider: script
    skip_cleanup: true
    script: aws s3 sync --region=eu-west-3 --delete --acl public-read dist/okty s3://okty
    on:
        repo: Okty-io/okty
        branch: dev

after_deploy:
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

