language: node_js
node_js:
- 9.10.1

before_script:
- npm install --only=prod

script:
- "./node_modules/.bin/ng build --prod --aot"

deploy:
  provider: s3
  access_key_id: AKIAJPRVJ7C4CKQQ2JVQ
  secret_access_key:
    secure: B1DLYQo7xT1jlOLkmaB22bUg9i/2hv89+swOLPx46tjHfyMbWV0DblNFcQUBuG0Fm5vf3Jwf7QdvLV9o4Y4hqxNKnlwY/5CV2OFf5lCC4oQGHUBqrnpP5tmGFgtV9EVxJailwx9IWqeahqb0NXNC4p7zd1PknlSqiifC1DS0HOyNWLrbBYj92ArL5GppSXAckMD8OvTX3i3/L32HqnjdvGDUiBkY9aJqvbikHMhnOxKyNgT4cjVPUnDBZBLwiL5Gs8UBf0LVA5AOKpqkEPG3vC9S6tcx0ri4cagLdRP0/sGMZYv12oSKOqeTg+WQy0UeV8uWhj1woPLpdxxAJRBr49eCZO8mYiywLI1hNQEFlMS/t0CfkV4fB9ZkL/BYfPaTVn3iz0FBOUkPyXlpqHZtz0KaUP16+To+SkEbMEt8djFm8VbirFLCUSmaE/EnWuR63z45lt598MaOka+fj41AycS0wvVVV0UilI9VbzmIZ/Al4wLsjM+sVgab6niCpaVAFf3IkNy1qjZR5x1XYmYmAy14mh08POmnPkES9LDlt0vmrmGjHKkrn5QRTwABOAeGbrlACdN4oTYtatlHHtpSDAkfPidhbF77aqyryiW3SGK807iC6a3T7PTbZx9IOyNxewnvA8WsR2SAuXJaENh1+hl19o59Yt2ml0nVJ1ZM0tg=
  bucket: okty
  local-dir: dist/okty
  acl: public_read
  skip_cleanup: true
  on:
    repo: Okty-io/okty
    branch: v2
